# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def github_pull_request_to_develop?
  ENV["GITHUB_ACTIONS"] == "true" &&
    ENV["GITHUB_EVENT_NAME"] == "pull_request" &&
    ENV["GITHUB_BASE_REF"] == "develop"
end

def firebase_option_env
  {
    app: "FIREBASE_IOS_APP_ID",
    testers: "FIREBASE_APP_DISTRIBUTION_TESTERS",
    firebase_cli_token: "FIREBASE_CLI_TOKEN",
    service_credentials_json_data: "FIREBASE_SERVICE_CREDENTIALS_JSON"
  }.each_with_object({}) do |(option, env_name), options|
    value = ENV[env_name].to_s.strip
    options[option] = value unless value.empty?
  end
end

def firebase_distribution_groups
  groups = ENV["FIREBASE_APP_DISTRIBUTION_GROUPS"].to_s.split(",").map(&:strip)
  (["internal"] + groups).reject(&:empty?).uniq.join(",")
end

def firebase_release_notes
  notes = ENV["FIREBASE_APP_DISTRIBUTION_RELEASE_NOTES"].to_s.strip
  return notes unless notes.empty?

  [
    "GitHub pull request build",
    "Base: #{ENV['GITHUB_BASE_REF']}",
    "Head: #{ENV['GITHUB_HEAD_REF']}",
    "SHA: #{ENV['GITHUB_SHA']}",
    "Run: #{ENV['GITHUB_SERVER_URL']}/#{ENV['GITHUB_REPOSITORY']}/actions/runs/#{ENV['GITHUB_RUN_ID']}"
  ].reject { |line| line.end_with?(": ") }.join("\n")
end

def firebase_build_number
  run_number = ENV["GITHUB_RUN_NUMBER"].to_s.strip
  return run_number unless run_number.empty?

  Time.now.utc.strftime("%Y%m%d%H%M")
end

def firebase_derived_data_path
  path = ENV["IOS_DERIVED_DATA_PATH"].to_s.strip
  path = "~/Library/Developer/Xcode/DerivedData/AsoBMaShow-FirebaseCI" if path.empty?
  File.expand_path(path)
end

def app_store_key_id
  key_id = ENV["APP_STORE_KEY_ID"].to_s.strip
  key_id.empty? ? "7459U6UPUW" : key_id
end

platform :ios do
  desc "Push a new beta build to Firebase App Distribution or TestFlight"
  lane :beta do
    distribute_to_firebase = github_pull_request_to_develop?
    match_type = distribute_to_firebase ? "adhoc" : "appstore"
    export_method = distribute_to_firebase ? "ad-hoc" : "app-store"

    unlock_keychain(
      password: ENV["KEYCHAIN_PASSWORD"]
    )
    api_key = app_store_connect_api_key(
      key_id: app_store_key_id,
      issuer_id: "5e03957a-e681-458f-8011-a8f608b71a70",
      key_content: ENV["APP_STORE_KEY"],
      duration: 1200,
      in_house: false,
    )
    match(type: match_type, git_basic_authorization: ENV["GIT_BASIC_AUTHORIZATION"], api_key: api_key)
    build_number = if distribute_to_firebase
                     firebase_build_number
                   else
                     latest_testflight_build_number(initial_build_number: 0) + 1
                   end

    xcargs = "-allowProvisioningUpdates CURRENT_PROJECT_VERSION=#{build_number}"
    build_options = {
      scheme: "AsoBMaShow",
      workspace: "AsoBMaShow.xcworkspace",
      export_method: export_method,
      xcargs: xcargs,
      clean: !distribute_to_firebase
    }

    if distribute_to_firebase
      build_options[:derived_data_path] = firebase_derived_data_path
    end

    build_app(**build_options)
    temporary_fix_ios_post_build

    if distribute_to_firebase
      firebase_options = firebase_option_env
      firebase_app_distribution(
        **firebase_options,
        groups: firebase_distribution_groups,
        release_notes: firebase_release_notes
      )
    else
      upload_to_testflight
    end
  end
end

desc "Temporary workaround to remove unwanted files from the IPA"
private_lane :temporary_fix_ios_post_build do
  # Workaround to remove ._Symbols from ipa.
  ipa_location = lane_context[SharedValues::IPA_OUTPUT_PATH]
  sh("unzip -l #{ipa_location} | grep ._Symbols || true")
  sh("zip -d #{ipa_location} ._Symbols/ || true")
end
