#pragma once

#include "music_select_skin_ledger_evidence.h"

#include <string>
#include <string_view>
#include <vector>

namespace music_select_runtime_ledger_assertions {

inline std::vector<std::string> forRunner(std::string_view runner) {
  if (runner == "lua_skin_runtime_tests") {
    return {
        "select.lua-loader.load-3",
        "select.lua-loader.load-header-1",
        "select.lua-loader.load-skin-3",
        "select.lua-loader.sandboxed-1",
    };
  }
  if (runner == "music_select_bar_manager_tests") {
    return {
        "select.behavior.music-selector.get-bar-manager-0",
        "select.behavior.music-selector.get-selected-bar-0",
        "select.behavior.music-selector.get-sort-0",
        "select.behavior.music-selector.select-1",
        "select.behavior.music-selector.set-sort-1",
        "select.constant.music-selector.all-mode",
        "select.constant.music-selector.difficulty",
        "select.constant.music-selector.mode",
        "select.constant.music-selector.replay",
    };
  }
  if (runner == "music_select_bar_renderer_tests") {
    return {
        "select.behavior.bar-renderer.dispose-0",
        "select.behavior.bar-renderer.input-0",
        "select.behavior.bar-renderer.mouse-pressed-4",
        "select.behavior.bar-renderer.prepare-2",
        "select.behavior.bar-renderer.render-2",
        "select.behavior.bar-renderer.reset-input-0",
        "select.behavior.music-selector.get-bar-render-0",
        "select.behavior.skin-bar.clear-text-layout-cache-0",
        "select.behavior.skin-bar.dispose-0",
        "select.behavior.skin-bar.draw-1",
        "select.behavior.skin-bar.draw-text-5",
        "select.behavior.skin-bar.get-bar-images-2",
        "select.behavior.skin-bar.get-barlevel-1",
        "select.behavior.skin-bar.get-graph-0",
        "select.behavior.skin-bar.get-label-1",
        "select.behavior.skin-bar.get-lamp-1",
        "select.behavior.skin-bar.get-player-lamp-1",
        "select.behavior.skin-bar.get-position-0",
        "select.behavior.skin-bar.get-rival-lamp-1",
        "select.behavior.skin-bar.get-text-1",
        "select.behavior.skin-bar.get-trophy-1",
        "select.behavior.skin-bar.prepare-2",
        "select.behavior.skin-bar.set-bar-image-2",
        "select.behavior.skin-bar.set-barlevel-2",
        "select.behavior.skin-bar.set-graph-1",
        "select.behavior.skin-bar.set-label-2",
        "select.behavior.skin-bar.set-lamp-2",
        "select.behavior.skin-bar.set-player-lamp-2",
        "select.behavior.skin-bar.set-rival-lamp-2",
        "select.behavior.skin-bar.set-skin-scale-2",
        "select.behavior.skin-bar.set-text-2",
        "select.behavior.skin-bar.set-trophy-2",
        "select.behavior.skin-bar.validate-0",
        "select.skin-bar.bar-count",
        "select.skin-bar.barlabel-count",
        "select.skin-bar.barlamp-count",
        "select.skin-bar.barlevel-count",
        "select.skin-bar.bartext-command",
        "select.skin-bar.bartext-count",
        "select.skin-bar.bartext-folder-new",
        "select.skin-bar.bartext-folder-normal",
        "select.skin-bar.bartext-grade",
        "select.skin-bar.bartext-new",
        "select.skin-bar.bartext-no-songs",
        "select.skin-bar.bartext-normal",
        "select.skin-bar.bartext-search",
        "select.skin-bar.bartext-song-new",
        "select.skin-bar.bartext-song-normal",
        "select.skin-bar.bartext-table",
        "select.skin-bar.bartrophy-count",
    };
  }
  if (runner == "music_select_event_controller_tests") {
    return {
        "select.behavior.music-selector.execute-1",
        "select.behavior.music-selector.select-song-1",
        "select.behavior.music-selector.set-panel-state-1",
        "select.behavior.music-selector.set-rival-1",
        "select.input.chart-replication-mode.none",
        "select.input.chart-replication-mode.replaychart",
        "select.input.chart-replication-mode.replayoption",
        "select.input.chart-replication-mode.rivalchart",
        "select.input.chart-replication-mode.rivaloption",
        "select.property.event.enum-event-type-autoplay",
        "select.property.event.enum-event-type-bga",
        "select.property.event.enum-event-type-bgaexpand",
        "select.property.event.enum-event-type-bottomshiftablegauge",
        "select.property.event.enum-event-type-chartreplicationmode",
        "select.property.event.enum-event-type-constant",
        "select.property.event.enum-event-type-difficulty",
        "select.property.event.enum-event-type-duration1p",
        "select.property.event.enum-event-type-extranotedepth",
        "select.property.event.enum-event-type-favorite-chart",
        "select.property.event.enum-event-type-favorite-song",
        "select.property.event.enum-event-type-gauge1p",
        "select.property.event.enum-event-type-gaugeautoshift",
        "select.property.event.enum-event-type-guidese",
        "select.property.event.enum-event-type-hidden",
        "select.property.event.enum-event-type-hispeed1p",
        "select.property.event.enum-event-type-hispeedautoadjust",
        "select.property.event.enum-event-type-hsfix",
        "select.property.event.enum-event-type-judgealgorithm",
        "select.property.event.enum-event-type-keyconfig",
        "select.property.event.enum-event-type-lanecover",
        "select.property.event.enum-event-type-lift",
        "select.property.event.enum-event-type-lnmode",
        "select.property.event.enum-event-type-longnotemode",
        "select.property.event.enum-event-type-minemode",
        "select.property.event.enum-event-type-mode",
        "select.property.event.enum-event-type-notesdisplaytiming",
        "select.property.event.enum-event-type-notesdisplaytimingautoadjust",
        "select.property.event.enum-event-type-open-document",
        "select.property.event.enum-event-type-open-download-site",
        "select.property.event.enum-event-type-open-ir",
        "select.property.event.enum-event-type-open-with-explorer",
        "select.property.event.enum-event-type-option1p",
        "select.property.event.enum-event-type-option2p",
        "select.property.event.enum-event-type-optiondp",
        "select.property.event.enum-event-type-play",
        "select.property.event.enum-event-type-practice",
        "select.property.event.enum-event-type-rival",
        "select.property.event.enum-event-type-scrollmode",
        "select.property.event.enum-event-type-seventonine-pattern",
        "select.property.event.enum-event-type-seventonine-type",
        "select.property.event.enum-event-type-skinconfig",
        "select.property.event.enum-event-type-songbar-sort",
        "select.property.event.enum-event-type-sort",
        "select.property.event.enum-event-type-target",
        "select.property.event.enum-event-type-update-folder",
        "select.property.event.method-change-auto-save-replay",
        "select.property.event.method-get-replay-event-consumer",
        "select.property.event.music-selector",
    };
  }
  if (runner == "music_select_input_processor_tests") {
    return {
        "select.behavior.music-select-input-processor.canceled-0",
        "select.behavior.music-select-input-processor.input-1",
        "select.behavior.music-selector.input-0",
    };
  }
  if (runner == "music_select_preview_tests") {
    return {
        "select.behavior.music-selector.selected-bar-moved-0",
        "select.property.writer.float-writer-contract",
        "select.property.writer.musicselect-position",
    };
  }
  if (runner == "music_select_property_projection_tests") {
    return {
        "select.behavior.music-selector.exists-constraint-1",
        "select.behavior.music-selector.get-1",
        "select.behavior.music-selector.get-panel-state-0",
        "select.behavior.music-selector.get-rival-0",
        "select.behavior.music-selector.get-selected-bar-play-config-0",
        "select.behavior.music-selector.get-selected-replay-0",
        "select.behavior.music-selector.set-selected-replay-1",
        "select.property.boolean.enum-boolean-type-compare-rival",
        "select.property.boolean.enum-boolean-type-constant",
        "select.property.boolean.enum-boolean-type-ir-busy",
        "select.property.boolean.enum-boolean-type-ir-failed",
        "select.property.boolean.enum-boolean-type-ir-no-player",
        "select.property.boolean.enum-boolean-type-ir-waiting",
        "select.property.boolean.enum-boolean-type-not-compare-rival",
        "select.property.boolean.enum-boolean-type-playablebar",
        "select.property.boolean.enum-boolean-type-randomcoursebar",
        "select.property.boolean.enum-boolean-type-randomselectbar",
        "select.property.boolean.enum-boolean-type-select-bar-not-played",
        "select.property.boolean.enum-boolean-type-select-coursebar",
        "select.property.boolean.enum-boolean-type-select-folderbar",
        "select.property.boolean.enum-boolean-type-select-panel1",
        "select.property.boolean.enum-boolean-type-select-panel2",
        "select.property.boolean.enum-boolean-type-select-panel3",
        "select.property.boolean.enum-boolean-type-select-replaydata-1",
        "select.property.boolean.enum-boolean-type-select-replaydata-2",
        "select.property.boolean.enum-boolean-type-select-replaydata-3",
        "select.property.boolean.enum-boolean-type-select-replaydata-4",
        "select.property.boolean.enum-boolean-type-select-somgbar",
        "select.property.boolean.method-create-course-data-constraint-property",
        "select.property.boolean.method-create-replay-property",
        "select.property.boolean.music-selector",
        "select.property.float.enum-rate-type-musicselect-position",
        "select.property.float.enum-rate-type-ranking-position",
        "select.property.float.method-create-irclear-rate-property",
        "select.property.float.method-create-irtotal-clear-rate-property",
        "select.property.float.method-create-judge-rate",
        "select.property.float.method-create-selected-score-rate",
        "select.property.float.method-get-level-rate",
        "select.property.float.music-selector",
        "select.property.integer.enum-index-type-cleartype",
        "select.property.integer.enum-index-type-cleartype-target",
        "select.property.integer.enum-index-type-constant",
        "select.property.integer.enum-index-type-difficulty",
        "select.property.integer.enum-index-type-hidden",
        "select.property.integer.enum-index-type-hispeedautoadjust",
        "select.property.integer.enum-index-type-judgealgorithm",
        "select.property.integer.enum-index-type-lanecover",
        "select.property.integer.enum-index-type-lift",
        "select.property.integer.enum-index-type-mode",
        "select.property.integer.enum-index-type-sort",
        "select.property.integer.enum-value-type-clearcount",
        "select.property.integer.enum-value-type-duration",
        "select.property.integer.enum-value-type-duration-green",
        "select.property.integer.enum-value-type-failcount",
        "select.property.integer.enum-value-type-ir-rank",
        "select.property.integer.enum-value-type-ir-update-waiting",
        "select.property.integer.enum-value-type-playcount",
        "select.property.integer.method-create-folder-clear-count-property",
        "select.property.integer.method-create-irclear-count-property",
        "select.property.integer.method-create-irclear-rate-property",
        "select.property.integer.method-create-irtotal-clear-count-property",
        "select.property.integer.method-create-irtotal-clear-rate-property",
        "select.property.integer.method-create-irtotal-player-property",
        "select.property.integer.method-create-max-combo-property",
        "select.property.integer.method-create-miss-count-property",
        "select.property.integer.method-create-rankin-cleartype-property",
        "select.property.integer.method-create-ranking-playertype-property",
        "select.property.integer.method-create-rankingexscore",
        "select.property.integer.method-create-rankingindex",
        "select.property.integer.method-get",
        "select.property.integer.method-get-current-score-data",
        "select.property.integer.music-selector",
        "select.property.string.enum-string-type-directory",
        "select.property.string.enum-string-type-fulltitle",
        "select.property.string.enum-string-type-rival",
        "select.property.string.enum-string-type-searchword",
        "select.property.string.enum-string-type-target",
        "select.property.string.enum-string-type-title",
        "select.property.string.method-create-coursetitle",
        "select.property.string.method-create-rankingname",
        "select.property.string.music-selector",
    };
  }
  if (runner == "music_select_ranking_tests") {
    return {
        "select.behavior.music-selector.get-current-ranking-data-0",
        "select.behavior.music-selector.get-current-ranking-duration-0",
        "select.behavior.music-selector.get-ranking-offset-0",
        "select.behavior.music-selector.get-ranking-position-0",
        "select.behavior.music-selector.set-ranking-position-1",
        "select.property.writer.ranking-position",
    };
  }
  if (runner == "music_select_repository_projection_tests") {
    return {
        "select.bar-behavior.bar.get-lamp-1",
        "select.bar-behavior.bar.get-rival-score-0",
        "select.bar-behavior.bar.get-score-0",
        "select.bar-behavior.bar.get-title-0",
        "select.bar-behavior.bar.set-rival-score-1",
        "select.bar-behavior.bar.set-score-1",
        "select.bar-behavior.command-bar.get-children-0",
        "select.bar-behavior.command-bar.get-title-0",
        "select.bar-behavior.command-bar.update-folder-status-0",
        "select.bar-behavior.container-bar.get-children-0",
        "select.bar-behavior.container-bar.get-title-0",
        "select.bar-behavior.directory-bar.clear-0",
        "select.bar-behavior.directory-bar.get-children-0",
        "select.bar-behavior.directory-bar.get-children-2",
        "select.bar-behavior.directory-bar.get-lamp-1",
        "select.bar-behavior.directory-bar.get-lamps-0",
        "select.bar-behavior.directory-bar.get-ranks-0",
        "select.bar-behavior.directory-bar.get-rival-lamps-0",
        "select.bar-behavior.directory-bar.is-show-invisible-chart-0",
        "select.bar-behavior.directory-bar.is-sortable-0",
        "select.bar-behavior.directory-bar.set-sortable-1",
        "select.bar-behavior.directory-bar.update-folder-status-0",
        "select.bar-behavior.executable-bar.filter-1",
        "select.bar-behavior.executable-bar.get-filter-0",
        "select.bar-behavior.executable-bar.get-lamp-1",
        "select.bar-behavior.executable-bar.get-name-0",
        "select.bar-behavior.executable-bar.get-song-data-0",
        "select.bar-behavior.executable-bar.get-title-0",
        "select.bar-behavior.executable-bar.set-filter-2",
        "select.bar-behavior.executable-bar.set-name-1",
        "select.bar-behavior.folder-bar.get-children-0",
        "select.bar-behavior.folder-bar.get-crc-0",
        "select.bar-behavior.folder-bar.get-folder-data-0",
        "select.bar-behavior.folder-bar.get-title-0",
        "select.bar-behavior.folder-bar.update-folder-status-0",
        "select.bar-behavior.grade-bar.exists-all-songs-0",
        "select.bar-behavior.grade-bar.get-course-data-0",
        "select.bar-behavior.grade-bar.get-lamp-1",
        "select.bar-behavior.grade-bar.get-mirror-score-0",
        "select.bar-behavior.grade-bar.get-random-score-0",
        "select.bar-behavior.grade-bar.get-song-datas-0",
        "select.bar-behavior.grade-bar.get-title-0",
        "select.bar-behavior.grade-bar.get-trophy-0",
        "select.bar-behavior.grade-bar.set-mirror-score-1",
        "select.bar-behavior.grade-bar.set-random-score-1",
        "select.bar-behavior.hash-bar.get-children-0",
        "select.bar-behavior.hash-bar.get-elements-0",
        "select.bar-behavior.hash-bar.get-title-0",
        "select.bar-behavior.hash-bar.set-elements-1",
        "select.bar-behavior.hash-bar.update-folder-status-0",
        "select.bar-behavior.random-course-bar.exists-all-songs-0",
        "select.bar-behavior.random-course-bar.get-course-data-0",
        "select.bar-behavior.random-course-bar.get-lamp-1",
        "select.bar-behavior.random-course-bar.get-song-datas-0",
        "select.bar-behavior.random-course-bar.get-title-0",
        "select.bar-behavior.same-folder-bar.get-children-0",
        "select.bar-behavior.same-folder-bar.get-title-0",
        "select.bar-behavior.search-word-bar.get-children-0",
        "select.bar-behavior.search-word-bar.get-title-0",
        "select.bar-behavior.search-word-bar.update-folder-status-0",
        "select.bar-behavior.selectable-bar.exists-replay-1",
        "select.bar-behavior.selectable-bar.exists-replay-data-0",
        "select.bar-behavior.selectable-bar.set-exists-replay-2",
        "select.bar-behavior.song-bar.exists-song-0",
        "select.bar-behavior.song-bar.get-banner-0",
        "select.bar-behavior.song-bar.get-lamp-1",
        "select.bar-behavior.song-bar.get-song-data-0",
        "select.bar-behavior.song-bar.get-stagefile-0",
        "select.bar-behavior.song-bar.get-title-0",
        "select.bar-behavior.song-bar.set-banner-1",
        "select.bar-behavior.song-bar.set-stagefile-1",
        "select.bar-behavior.song-bar.to-song-bar-array-1",
        "select.bar-behavior.table-bar.get-accessor-0",
        "select.bar-behavior.table-bar.get-children-0",
        "select.bar-behavior.table-bar.get-grades-0",
        "select.bar-behavior.table-bar.get-levels-0",
        "select.bar-behavior.table-bar.get-title-0",
        "select.bar-behavior.table-bar.get-url-0",
        "select.bar-behavior.table-bar.set-table-data-1",
        "select.bar-class.bar",
        "select.bar-class.command-bar",
        "select.bar-class.container-bar",
        "select.bar-class.directory-bar",
        "select.bar-class.executable-bar",
        "select.bar-class.folder-bar",
        "select.bar-class.grade-bar",
        "select.bar-class.hash-bar",
        "select.bar-class.random-course-bar",
        "select.bar-class.same-folder-bar",
        "select.bar-class.search-word-bar",
        "select.bar-class.selectable-bar",
        "select.bar-class.song-bar",
        "select.bar-class.table-bar",
        "select.behavior.music-selector.get-rival-score-data-cache-0",
        "select.behavior.music-selector.get-score-data-cache-0",
        "select.behavior.music-selector.get-song-database-0",
    };
  }
  if (runner == "music_select_search_history_tests") {
    return {
        "select.behavior.music-selector.search-1",
    };
  }
  if (runner == "music_select_skin_model_tests") {
    return {
        "select.behavior.music-select-skin.get-center-bar-0",
        "select.behavior.music-select-skin.get-clickable-bar-0",
        "select.behavior.music-select-skin.get-search-text-region-0",
        "select.behavior.music-select-skin.set-center-bar-1",
        "select.behavior.music-select-skin.set-clickable-bar-1",
        "select.behavior.music-select-skin.set-search-text-region-1",
        "select.loader.json-select.get-skin-1",
        "select.loader.json-select.load-skin-object-4",
    };
  }
  if (runner == "music_select_skin_state_bridge_tests") {
    return {
        "select.property.timer.main-state-timer",
    };
  }
  if (runner == "play_skin_session_tests") {
    return {
        "select.behavior.music-selector.create-0",
        "select.behavior.music-selector.dispose-0",
        "select.behavior.music-selector.get-banner-resource-0",
        "select.behavior.music-selector.get-stagefile-resource-0",
        "select.behavior.music-selector.load-selected-song-images-0",
        "select.behavior.music-selector.prepare-0",
        "select.behavior.music-selector.render-0",
        "select.behavior.music-selector.shutdown-0",
        "select.loader.music-select-dispatch",
    };
  }
  if (runner == "skin_draw_command_tests") {
    return {
        "select.behavior.skin-distribution-graph.dispose-0",
        "select.behavior.skin-distribution-graph.draw-1",
        "select.behavior.skin-distribution-graph.draw-4",
        "select.behavior.skin-distribution-graph.prepare-2",
    };
  }
  return {};
}

inline void appendForRunner(std::string_view runner,
                            std::vector<std::string> &identifiers) {
  auto extra = forRunner(runner);
  identifiers.insert(identifiers.end(), extra.begin(), extra.end());
}

inline int finish(int argc, char **argv, std::string_view runner, int failures,
                  std::string_view failureLabel,
                  std::string_view successMessage) {
  return music_select_skin_ledger_evidence::finish(
      argc, argv, runner, failures, forRunner(runner), failureLabel,
      successMessage);
}

} // namespace music_select_runtime_ledger_assertions
