platform :ios, '14.0'

target 'AsoBMaShow' do
  pod 'Yoga', :git => 'https://github.com/facebook/yoga.git'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
