target_sources(main PRIVATE
    ChartFilterSortPanelView.cpp
    ChartViewerScene.cpp
    MainMenuLibrary.cpp
    MainMenuScene.cpp
    MusicPlayerScene.cpp
    SceneManager.cpp
    ResultScene.cpp
    SettingsScene.cpp
    SettingsSceneControls.cpp
    SettingsSceneLayout.cpp
    SettingsScenePreview.cpp
    SettingsSceneTables.cpp
)
add_subdirectory(play)
