include_guard(GLOBAL)

function(asobmashow_dependency_file path output)
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        message(FATAL_ERROR "Missing Android dependency input: ${path}")
    endif()
    file(REAL_PATH "${path}" canonical)
    file(SHA256 "${canonical}" digest)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${canonical}")
    set(${output} "${${output}}${canonical}=${digest}\n" PARENT_SCOPE)
endfunction()

function(asobmashow_dependency_tree path output)
    if(NOT IS_DIRECTORY "${path}")
        message(FATAL_ERROR "Missing Android dependency directory: ${path}")
    endif()
    file(REAL_PATH "${path}" canonical)
    file(GLOB_RECURSE files CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE "${canonical}/*")
    list(SORT files)
    set(contents "${${output}}directory=${canonical}\n")
    foreach(path IN LISTS files)
        # Interpreter caches and desktop metadata do not affect dependencies.
        if(NOT path MATCHES "(/__pycache__/|\\.pyc$|/\\.DS_Store$)")
            asobmashow_dependency_file("${path}" contents)
        endif()
    endforeach()
    set(${output} "${contents}" PARENT_SCOPE)
endfunction()

# Overlay paths in a registry configuration are relative to that manifest.
function(asobmashow_dependency_configuration json root output)
    set(contents "${${output}}")
    foreach(field overlay-ports overlay-triplets)
        string(JSON count ERROR_VARIABLE error LENGTH "${json}" "${field}")
        if(NOT error AND count GREATER 0)
            math(EXPR last "${count} - 1")
            foreach(index RANGE ${last})
                string(JSON directory GET "${json}" "${field}" ${index})
                file(REAL_PATH "${directory}" canonical BASE_DIRECTORY "${root}")
                asobmashow_dependency_tree("${canonical}" contents)
            endforeach()
        endif()
    endforeach()
    set(${output} "${contents}" PARENT_SCOPE)
endfunction()

# Runs only in the top-level Android project, before project() loads vcpkg.
# The native objects remain in AGP's configuration-specific build directories.
function(asobmashow_prepare_android_dependencies)
    foreach(required CMAKE_TOOLCHAIN_FILE VCPKG_CHAINLOAD_TOOLCHAIN_FILE
                     VCPKG_TARGET_TRIPLET ANDROID_ABI ANDROID_PLATFORM ANDROID_STL)
        if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
            message(FATAL_ERROR "Android dependency sharing requires ${required}")
        endif()
    endforeach()
    file(REAL_PATH "${CMAKE_TOOLCHAIN_FILE}" toolchain)
    file(REAL_PATH "${VCPKG_CHAINLOAD_TOOLCHAIN_FILE}" chainload)
    get_filename_component(toolchain_directory "${toolchain}" DIRECTORY)
    get_filename_component(chainload_directory "${chainload}" DIRECTORY)
    file(REAL_PATH "${toolchain_directory}/../.." vcpkg_root)
    file(REAL_PATH "${chainload_directory}/../.." ndk_root)

    set(inputs "android-dependency-cache-v1\n")
    asobmashow_dependency_file("${toolchain}" inputs)
    asobmashow_dependency_file("${chainload}" inputs)
    asobmashow_dependency_file("${ndk_root}/source.properties" inputs)
    asobmashow_dependency_tree("${ndk_root}/build/cmake" inputs)
    if(VCPKG_MANIFEST_DIR)
        file(REAL_PATH "${VCPKG_MANIFEST_DIR}" manifest_root)
    else()
        set(manifest_root "${CMAKE_SOURCE_DIR}")
    endif()
    asobmashow_dependency_file("${manifest_root}/vcpkg.json" inputs)
    file(READ "${manifest_root}/vcpkg.json" manifest)
    foreach(field configuration vcpkg-configuration)
        string(JSON embedded ERROR_VARIABLE error GET "${manifest}" "${field}")
        if(NOT error)
            asobmashow_dependency_configuration("${embedded}" "${manifest_root}" inputs)
        endif()
    endforeach()
    # A missing file in CMAKE_CONFIGURE_DEPENDS is not watched by Ninja.
    # Watch the optional file's presence as well as its contents.
    file(GLOB registry_configuration CONFIGURE_DEPENDS
        "${manifest_root}/vcpkg-configuration.json")
    foreach(path IN LISTS registry_configuration)
        asobmashow_dependency_file("${path}" inputs)
        file(READ "${path}" configuration)
        asobmashow_dependency_configuration("${configuration}" "${manifest_root}" inputs)
    endforeach()
    foreach(variable VCPKG_OVERLAY_PORTS VCPKG_OVERLAY_TRIPLETS)
        foreach(directory IN LISTS ${variable})
            asobmashow_dependency_tree("${directory}" inputs)
        endforeach()
        # vcpkg also consumes these environment path lists, independently of
        # the CMake variables (colon-separated on Unix, semicolon on Windows).
        file(TO_CMAKE_PATH "$ENV{${variable}}" environment_directories)
        foreach(directory IN LISTS environment_directories)
            asobmashow_dependency_tree("${directory}" inputs)
        endforeach()
    endforeach()
    asobmashow_dependency_tree("${vcpkg_root}/scripts" inputs)
    asobmashow_dependency_tree("${vcpkg_root}/triplets" inputs)
    if(CMAKE_HOST_WIN32)
        asobmashow_dependency_file("${vcpkg_root}/vcpkg.exe" inputs)
    else()
        asobmashow_dependency_file("${vcpkg_root}/vcpkg" inputs)
    endif()

    find_program(dependency_git git REQUIRED)
    execute_process(COMMAND "${dependency_git}" -C "${vcpkg_root}" rev-parse HEAD
        RESULT_VARIABLE git_result OUTPUT_VARIABLE revision
        ERROR_VARIABLE git_error OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT git_result EQUAL 0)
        message(FATAL_ERROR "Cannot identify vcpkg checkout: ${git_error}")
    endif()
    # The pinned revision covers pristine builtin ports; include local edits too.
    execute_process(COMMAND "${dependency_git}" -C "${vcpkg_root}" diff --binary HEAD -- ports
        RESULT_VARIABLE diff_result OUTPUT_VARIABLE port_changes ERROR_VARIABLE git_error)
    execute_process(COMMAND "${dependency_git}" -C "${vcpkg_root}"
        ls-files --others --exclude-standard -- ports
        RESULT_VARIABLE untracked_result OUTPUT_VARIABLE untracked_ports
        ERROR_VARIABLE untracked_error OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT diff_result EQUAL 0 OR NOT untracked_result EQUAL 0)
        message(FATAL_ERROR "Cannot inspect vcpkg port changes: ${git_error}${untracked_error}")
    endif()
    string(SHA256 port_digest "${port_changes}")
    string(APPEND inputs "vcpkg-revision=${revision}\nvcpkg-port-changes=${port_digest}\n")
    if(untracked_ports)
        string(REPLACE "\n" ";" untracked_ports "${untracked_ports}")
        foreach(path IN LISTS untracked_ports)
            asobmashow_dependency_file("${vcpkg_root}/${path}" inputs)
        endforeach()
    endif()
    cmake_host_system_information(RESULT host_platform QUERY OS_PLATFORM)
    string(APPEND inputs "host=${CMAKE_HOST_SYSTEM_NAME}/${host_platform}\n")
    foreach(variable VCPKG_TARGET_TRIPLET VCPKG_HOST_TRIPLET
                     VCPKG_MANIFEST_FEATURES VCPKG_MANIFEST_NO_DEFAULT_FEATURES
                     ANDROID_ABI ANDROID_PLATFORM ANDROID_STL)
        string(APPEND inputs "${variable}=${${variable}}\n")
    endforeach()
    foreach(variable CC CXX VCPKG_DEFAULT_HOST_TRIPLET VCPKG_KEEP_ENV_VARS)
        string(APPEND inputs "env:${variable}=$ENV{${variable}}\n")
    endforeach()
    string(SHA256 identity "${inputs}")
    set(directory "${CMAKE_SOURCE_DIR}/.cache/android-vcpkg/${identity}")
    file(MAKE_DIRECTORY "${directory}")
    set(ASOBMASHOW_DEPENDENCY_LOCK_TIMEOUT 600 CACHE STRING
        "Seconds to wait for an Android dependency installation")
    set(lock "${directory}/install.lock")
    file(LOCK "${lock}" GUARD PROCESS TIMEOUT ${ASOBMASHOW_DEPENDENCY_LOCK_TIMEOUT}
        RESULT_VARIABLE lock_result)
    if(NOT lock_result STREQUAL "0")
        message(FATAL_ERROR "Cannot acquire Android dependency lock ${lock}: ${lock_result}")
    endif()
    set_property(GLOBAL PROPERTY ASOBMASHOW_ANDROID_DEPENDENCY_LOCK "${lock}")
    file(WRITE "${directory}/inputs.txt" "${inputs}")

    set(installed "${directory}/installed")
    # CMake find_package/find_library results can otherwise retain paths into
    # the preceding identity after an overlay or manifest changes in-place.
    if(VCPKG_INSTALLED_DIR AND NOT VCPKG_INSTALLED_DIR STREQUAL installed)
        set(previous "${VCPKG_INSTALLED_DIR}")
        get_cmake_property(cache_variables CACHE_VARIABLES)
        foreach(variable IN LISTS cache_variables)
            string(FIND "${${variable}}" "${previous}/" old_prefix)
            if(NOT old_prefix EQUAL -1 OR "${${variable}}" STREQUAL previous)
                unset(${variable} CACHE)
            endif()
        endforeach()
    endif()
    set(VCPKG_INSTALLED_DIR "${installed}" CACHE PATH "Shared Android dependencies" FORCE)
    message(STATUS "Android dependencies: ${installed}")
endfunction()

function(asobmashow_release_android_dependencies)
    get_property(lock GLOBAL PROPERTY ASOBMASHOW_ANDROID_DEPENDENCY_LOCK)
    if(lock)
        file(LOCK "${lock}" RELEASE)
        set_property(GLOBAL PROPERTY ASOBMASHOW_ANDROID_DEPENDENCY_LOCK "")
    endif()
endfunction()
