# Explicitly selected high-duplication sources and their test consumers.
# SharedTestSources partitions these by their complete target compile contract;
# fixtures, uncommon sources, and the application remain independently compiled.
include("${CMAKE_CURRENT_LIST_DIR}/SharedTestSources.cmake")

asobmashow_share_test_sources(dependencies
    SOURCES
        src/AppSettingsStore.cpp
        src/ArchiveFile.cpp
        src/AtomicFile.cpp
        src/ChartLibraryScanner.cpp
        src/ChartScanWorkScheduler.cpp
        src/CourseIdentity.cpp
        src/DifficultyTableImporter.cpp
        src/FileChecksum.cpp
        src/MinizBridge.c
        src/ModernResult.cpp
        src/PrepMetronome.cpp
        src/ResultPersistenceCoordinator.cpp
        src/ResultPersistenceModel.cpp
        src/ResultRecordSummary.cpp
        src/ScoreProvenance.cpp
        src/Utils.cpp
        src/Uuid.cpp
        src/VersionedJson.cpp
        src/archive/IndexBuildCoordinator.cpp
        src/archive/TemporaryCache.cpp
        src/archive/UnzipOutput.cpp
        src/audio/AudioBackend.cpp
        src/audio/AudioDeviceManager.cpp
        src/audio/AudioMix.cpp
        src/audio/AudioWrapper.cpp
        src/audio/ClubBeat.cpp
        src/audio/GameplayBgaMissStateTracker.cpp
        src/audio/Jukebox.cpp
        src/audio/PrepMetronomeSound.cpp
        src/audio/decoder.cpp
        src/bms_parser.cpp
        src/ir/IrCredentialBackend.cpp
        src/ir/IrCredentialStore.cpp
        src/ir/IrOutboxModels.cpp
        src/ir/IrProfileSettings.cpp
        src/ir/IrRankingModal.cpp
        src/ir/IrReceiptModels.cpp
        src/ir/IrRemoteScoreModels.cpp
        src/ir/IrScoreReconciliation.cpp
        src/ir/IrSettingsPresentation.cpp
        src/ir/IrSubmission.cpp
        src/ir/IrSubmissionModern.cpp
        src/ir/IrSubmissionSnapshot.cpp
        src/ir/IrUploadCandidates.cpp
        src/ir/tachi/TachiBatchManual.cpp
        src/library/ArchiveUnzipRecovery.cpp
        src/music_select/MusicSelectBarManager.cpp
        src/music_select/MusicSelectPagedSongs.cpp
        src/music_select/MusicSelectPhysicalDirectory.cpp
        src/music_select/MusicSelectPropertyProjection.cpp
        src/music_select/MusicSelectReplaySlots.cpp
        src/music_select/MusicSelectRepositoryMetadataLoader.cpp
        src/music_select/MusicSelectRepositoryProjection.cpp
        src/music_select/MusicSelectSongIndex.cpp
        src/music_select/MusicSelectSqlSongs.cpp
        src/path.cpp
        src/practice/PracticeAnalytics.cpp
        src/practice/PracticeConfiguration.cpp
        src/practice/PracticeResultModel.cpp
        src/practice/PracticeSession.cpp
        src/rendering/Color.cpp
        src/rendering/SimpleBatchRenderer.cpp
        src/rendering/UiBatchRenderer.cpp
        src/rendering/UniformCache.cpp
        src/rendering/common.cpp
        src/replay/Base64Url.cpp
        src/replay/BeatorajaReplayCodec.cpp
        src/replay/BeatorajaReplayPath.cpp
        src/replay/ChartReplayAgreement.cpp
        src/replay/CourseReplayAgreement.cpp
        src/replay/GzipCodec.cpp
        src/replay/ReplayCapabilities.cpp
        src/replay/ReplayFileActionService.cpp
        src/replay/ReplayFileAssociationCoordinator.cpp
        src/replay/ReplayFileLifecycle.cpp
        src/replay/ReplayFileStore.cpp
        src/replay/ReplayPlayback.cpp
        src/replay/ReplayPlaybackDriver.cpp
        src/replay/ReplayPlaybackMaterializer.cpp
        src/replay/ReplayProfileInventory.cpp
        src/replay/ReplayReferenceAgreement.cpp
        src/replay/ReplaySetup.cpp
        src/replay/ReplaySetupAdapter.cpp
        src/replay/ReplaySetupProvenance.cpp
        src/repositories/ChartRepository.cpp
        src/repositories/ChartRepositoryDifficulty.cpp
        src/repositories/ChartRepositoryQueries.cpp
        src/repositories/ChartScanStore.cpp
        src/repositories/ChartStorageIdentity.cpp
        src/repositories/ReplayRepository.cpp
        src/repositories/ReplayRepositoryIrOutbox.cpp
        src/repositories/ReplayRepositoryIrRemoteScores.cpp
        src/repositories/ReplayRepositoryLegacyMigration.cpp
        src/repositories/ReplayRepositoryModernResults.cpp
        src/repositories/ReplayRepositoryRecords.cpp
        src/repositories/ReplayRepositorySchema.cpp
        src/repositories/ScoreRepository.cpp
        src/repositories/ScoreRepositoryChartSession.cpp
        src/repositories/ScoreRepositoryIrImport.cpp
        src/repositories/ScoreRepositoryQueries.cpp
        src/repositories/ScoreRepositorySchema.cpp
        src/scene/play/CompiledGameplayJudge.cpp
        src/scene/play/GameplayCandidateRules.cpp
        src/scene/play/GameplayDefinition.cpp
        src/scene/play/GameplayGaugeRules.cpp
        src/scene/play/GameplayJudgeRules.cpp
        src/scene/play/GameplayNoteJudgeRole.cpp
        src/scene/play/GameplayRulesetPolicy.cpp
        src/scene/play/GameplaySimulation.cpp
        src/scene/play/Judge.cpp
        src/scene/play/PlayfieldChartVisualModel.cpp
        src/scene/play/PlayfieldProjection.cpp
        src/scene/play/RhythmLaneInputController.cpp
        src/scene/play/SkinGameplayGraphState.cpp
        src/settings/AudioVideoSettings.cpp
        src/skin/SkinProfileSettings.cpp
        src/skin/SkinStoragePaths.cpp
        src/skin/beatoraja/GameplaySkinDocumentLoader.cpp
        src/skin/beatoraja/JsonGameplaySkinDecoder.cpp
        src/skin/beatoraja/Lr2GameplaySkinDecoder.cpp
        src/skin/beatoraja/LuaSkinAudioHost.cpp
        src/skin/beatoraja/LuaSkinBindingDecoder.cpp
        src/skin/beatoraja/LuaSkinFileSystem.cpp
        src/skin/beatoraja/LuaSkinHostModules.cpp
        src/skin/beatoraja/LuaSkinHttpClient.cpp
        src/skin/beatoraja/LuaSkinJavaPatternPcre2.cpp
        src/skin/beatoraja/LuaSkinLegacyInputHost.cpp
        src/skin/beatoraja/LuaSkinRuntime.cpp
        src/skin/beatoraja/LuaSkinTableDecoder.cpp
        src/skin/beatoraja/MusicSelectBarRenderer.cpp
        src/skin/beatoraja/NumericGlyphAtlas.cpp
        src/skin/beatoraja/PlaySkinSession.cpp
        src/skin/beatoraja/PlaySkinStateBridge.cpp
        src/skin/beatoraja/PlaySkinViewport.cpp
        src/skin/beatoraja/PomyuCharaResource.cpp
        src/skin/beatoraja/Skin2DRenderer.cpp
        src/skin/beatoraja/SkinAcceptanceRecorder.cpp
        src/skin/beatoraja/SkinBitmapFontParser.cpp
        src/skin/beatoraja/SkinBpmGraphRenderer.cpp
        src/skin/beatoraja/SkinCompatibilityDiagnostics.cpp
        src/skin/beatoraja/SkinCoverNormalization.cpp
        src/skin/beatoraja/SkinDecodeCache.cpp
        src/skin/beatoraja/SkinDestinationEvaluator.cpp
        src/skin/beatoraja/SkinGaugeGraphRenderer.cpp
        src/skin/beatoraja/SkinGaugeNodeExpansion.cpp
        src/skin/beatoraja/SkinHitErrorVisualizerRenderer.cpp
        src/skin/beatoraja/SkinJudgeNormalization.cpp
        src/skin/beatoraja/SkinJudgeNumberNormalization.cpp
        src/skin/beatoraja/SkinModelValidator.cpp
        src/skin/beatoraja/SkinMovieCatalog.cpp
        src/skin/beatoraja/SkinMovieCatalogFrame.cpp
        src/skin/beatoraja/SkinNoteDistributionGraphRenderer.cpp
        src/skin/beatoraja/SkinNoteLaneGeometryNormalization.cpp
        src/skin/beatoraja/SkinNoteLineNormalization.cpp
        src/skin/beatoraja/SkinNoteNormalization.cpp
        src/skin/beatoraja/SkinObjectResolutionPrecedence.cpp
        src/skin/beatoraja/SkinOverlayDigestProvider.cpp
        src/skin/beatoraja/SkinPerformanceTelemetry.cpp
        src/skin/beatoraja/SkinResourceCatalog.cpp
        src/skin/beatoraja/SkinTextAtlas.cpp
        src/skin/beatoraja/SkinTextGraphNormalization.cpp
        src/skin/beatoraja/SkinTimingVisualizerRenderer.cpp
        src/skin/package/SkinAliasDetector.cpp
        src/skin/package/SkinPackageCatalog.cpp
        src/skin/package/SkinPathPolicy.cpp
        src/skin/package/SkinTreeSnapshotter.cpp
        src/sqlite3.c
        src/utils/Stopwatch.cpp
        src/video/VideoDecodeState.cpp
        src/video/VideoFrameLayout.cpp
        src/video/VideoPlayer.cpp
        src/view/Button.cpp
        src/view/CheckboxButtonContent.cpp
        src/view/DecodedImageCache.cpp
        src/view/ImageDecodeCoordinator.cpp
        src/view/ImageFade.cpp
        src/view/ImageFileDecoder.cpp
        src/view/ImageView.cpp
        src/view/ScrollView.cpp
        src/view/SdlTtfRuntime.cpp
        src/view/TextView.cpp
        src/view/View.cpp
    TARGETS
        app_settings_store_tests
        application_ui_state_store_tests
        archive_file_concurrency_tests
        archive_unzip_modal_tests
        archive_unzip_operation_tests
        audio_mix_tests
        audio_video_settings_tests
        audio_wrapper_lifecycle_tests
        beatoraja_gameplay_cross_format_tests
        beatoraja_replay_codec_tests
        beatoraja_skin_model_tests
        best_replay_load_tests
        best_replay_resolver_tests
        bokutachi_cache_store_tests
        bounded_duration_graph_tests
        builtin_renderer_characterization_tests
        button_enabled_tests
        chart_audio_renderer_tests
        chart_filter_sort_panel_view_tests
        chart_library_operations_tests
        chart_library_scanner_tests
        chart_list_item_view_tests
        chart_meta_index_order_tests
        chart_practice_range_tests
        chart_preload_worker_tests
        chart_record_filters_tests
        chart_replay_context_tests
        chart_replay_persistence_tests
        chart_repository_tests
        chart_selector_query_tests
        checkbox_button_content_tests
        club_beat_tests
        context_menu_view_tests
        course_continuation_tests
        course_gameplay_session_builder_tests
        course_identity_tests
        course_replay_capture_tests
        course_replay_consumer_tests
        course_replay_context_tests
        course_replay_persistence_tests
        decide_loading_overlay_tests
        difficulty_table_importer_tests
        dropdown_view_tests
        file_checksum_tests
        find_bms_download_tests
        gameplay_automatic_authority_tests
        gameplay_bga_target_tests
        gameplay_gauge_rules_tests
        gameplay_playback_startup_tests
        gameplay_practice_input_boundary_tests
        gameplay_ruleset_policy_tests
        gameplay_ruleset_tests
        gameplay_score_state_tests
        gameplay_simulation_tests
        gameplay_skin_acceptance_controller_tests
        gameplay_skin_lifecycle_tests
        gameplay_skin_loading_benchmark_tests
        gameplay_skin_session_factory_tests
        gameplay_skin_settings_tests
        gameplay_skin_validator_tests
        gameplay_terminal_scene_tests
        gbattle_tests
        graph_result_tests
        graph_selector_tests
        graph_simulation_tests
        image_decode_coordinator_tests
        image_file_decoder_tests
        image_view_fade_tests
        ir_credential_migration_tests
        ir_credential_store_tests
        ir_driver_tests
        ir_ranking_modal_tests
        ir_ranking_service_tests
        ir_result_presentation_tests
        ir_saved_result_batch_upload_tests
        ir_saved_result_upload_tests
        ir_score_import_projection_tests
        ir_score_reconciliation_tests
        ir_settings_presentation_tests
        ir_submission_service_tests
        ir_submission_snapshot_tests
        ir_upload_candidate_list_view_tests
        ir_upload_candidates_tests
        ir_uploads_controller_tests
        json_gameplay_skin_decoder_tests
        jukebox_restore_tests
        legacy_result_summary_tests
        logical_gameplay_input_tests
        lr2_gameplay_skin_decoder_tests
        lr2_skin_csv_parser_tests
        lua_music_select_skin_decoder_tests
        lua_skin_binding_decoder_tests
        lua_skin_binding_live_integration_tests
        lua_skin_coroutine_tests
        lua_skin_file_system_tests
        lua_skin_gauge_live_integration_tests
        lua_skin_host_modules_tests
        lua_skin_java_pattern_tests
        lua_skin_note_live_integration_tests
        lua_skin_runtime_tests
        lua_skin_table_decoder_tests
        lua_skin_text_graph_live_integration_tests
        main_menu_library_tests
        modern_result_recall_tests
        modern_result_tests
        music_playlist_repository_tests
        music_select_bar_manager_tests
        music_select_paged_songs_tests
        music_select_preview_tests
        music_select_repository_projection_tests
        music_select_song_index_tests
        music_select_sql_songs_tests
        music_select_toolbar_view_tests
        numeric_glyph_model_validator_tests
        pending_ir_credential_cleanup_tests
        play_option_summary_tests
        play_options_panel_view_tests
        play_skin_session_tests
        play_skin_state_bridge_tests
        play_skin_touch_geometry_tests
        player_profile_manager_tests
        playfield_chart_visual_model_tests
        playfield_projection_tests
        playfield_visual_state_tests
        practice_analytics_tests
        practice_configuration_tests
        practice_launch_tests
        practice_preset_store_tests
        practice_result_flow_tests
        practice_result_model_tests
        practice_rule_override_tests
        practice_session_tests
        prep_metronome_tests
        preparation_plan_tests
        profile_archive_tests
        profile_settings_persistence_tests
        profile_switch_tests
        realtime_gameplay_worker_tests
        remote_result_scene_tests
        replay_codec_primitive_tests
        replay_codec_store_contract_tests
        replay_file_action_service_tests
        replay_file_store_tests
        replay_keysound_schedule_tests
        replay_legacy_migration_tests
        replay_playback_driver_tests
        replay_playback_tests
        replay_playfield_presentation_tests
        replay_profile_transfer_tests
        replay_record_filters_tests
        replay_records_modal_tests
        replay_repository_modern_chart_tests
        replay_repository_modern_course_tests
        replay_setup_tests
        replay_summary_list_tests
        replay_summary_list_view_tests
        result_image_exporter_partial_tests
        result_persistence_model_tests
        result_presentation_model_tests
        result_record_list_view_tests
        result_record_summary_tests
        score_cache_query_tests
        score_provenance_db_tests
        score_provenance_tests
        settings_cache_maintenance_tests
        settings_preview_chart_tests
        skin_acceptance_recorder_tests
        skin_archive_importer_tests
        skin_commit_coordinator_tests
        skin_diagnostic_history_tests
        skin_draw_command_tests
        skin_movie_catalog_types_tests
        skin_movie_clock_tests
        skin_overlay_digest_provider_tests
        skin_package_operation_service_tests
        skin_package_store_tests
        skin_resource_catalog_tests
        skin_sound_bundle_decode_tests
        skin_tree_snapshotter_tests
        tachi_batch_manual_tests
        tachi_driver_tests
        tachi_ranking_parser_tests
        temporary_archive_cache_tests
        text_input_box_tests
        text_view_font_lifetime_tests
        ui_batch_renderer_tests
        unzip_output_tests
        view_layout_tests
        visual_catch_up_tests
        worker_pool_startup_failure_tests
)
